# docker-compose --env-file .env.dev -f docker-compose-dev.yml up -d --build
# 1. users 테이블 생성
# 2. id, name column 추가
# 만약 워크벤치에서 볼륨을 보지 못한다면 포트를 확인해서 kill 한다음에 다시해보기
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - wonni-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 여기에 추가
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s

volumes:
  wonni-vol:
